In [4]:
# Задание 1
import numpy as np

# Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
a.shape

(5, 2)

In [9]:
mean_a = a.mean(axis=0) # Среднее арифметическое столбцов (axis=0)

In [10]:
mean_a

array([2. , 8.4])

In [12]:
# Задание 2
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [56]:
# Задание 3
a_col1 = a_centered[:, 0:1] # разделим столбцы, для более понятных расчетов (можно и без разделения)
#a_col1=np.transpose(a_col1) # можно для удобства перевести в строку
a_col1


array([-1.,  0.,  1.,  1., -1.])

In [55]:
a_col2 = a_centered[:, 1:]
#a_col2=np.transpose(a_col2)
a_col2


array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [51]:
# Скалярное произведение

# Вариант 1. Вручную через цикл
a_centered_sp = 0
for i in range(5):
    a_centered_sp = a_centered_sp + a_col1[i] * a_col2[i]
a_centered_sp = a_centered_sp[0] # Что бы получилось число, а не массив из одного элемента
a_centered_sp

(5, 1) (5, 1)


8.0

In [61]:
# Вариант 2 Через np.dot
a_centered_sp = np.dot(a_col1, a_col2)
a_centered_sp
# Выходит ошибка о несоответствующих размерностях. Проверим приведем их впорядок в следующей ячейке.


ValueError: shapes (5,1) and (5,1) not aligned: 1 (dim 1) != 5 (dim 0)

In [62]:
print (a_col1.shape, a_col2.shape) # проверим размерность сами
a_col12 = np.array([a_centered[i,0] for i in range(5)]) # Т.к. a_col1 (и а_col2 соответственно тоже) - двухмерные массивы,
# то сделаем одномерные, т.е. по-сути вектора
a_col12
a_col22 = np.array([a_centered[i,1] for i in range(5)])
a_col22

(5, 1) (5, 1)


array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [64]:
a_centered_sp = np.dot(a_col12,a_col22)
a_centered_sp

8.0

In [65]:
# Вариант 3
a_centered_sp = a_col12 @ a_col22
a_centered_sp

8.0

In [67]:
# Поделим на N-1 строк
a_centered_sp_N = a_centered_sp / (a.shape[0]-1)
a_centered_sp_N

2.0

In [70]:
# Задание 4
# Необходимо вычислить ковариацию с помощью np.cov и сравнить с тем что получилось выше. Элемент массива для сравнения - [0,1]
a_cov=np.cov(np.transpose(a))
a_cov[0,1]

2.0